### PR TITLE
Fix fetchActiveActions without param page

### PR DESCRIPTION
**Pull request by EnchStudio**

### CODE REVIEW

**Comment by EnchStudio** [comment]
@FC5570

**Review by FC5570 — COMMENTED** [review]
Could please describe why this change was made?

**Review by FC5570 — CHANGES_REQUESTED** [review]
- Please remove the dist folder
- Please remove the "Fixed version" heading from the Readme file
- Please remove the "author" field from package.json, and revert the version bump.

**Comment by EnchStudio** [comment]
hypixel have so many auctions that they can be displayed in one page, so you should pass a `page` param to get auctions for special page.
sry but i dont have enough time for this project, so i just forked one.
so you can do these change easily, and close my pr thx

**Comment by EnchStudio** [comment]
> * Please remove the dist folder请删除 dist 文件夹
> * Please remove the "Fixed version" heading from the Readme file请从自述文件中删除“固定版本”标题
> * Please remove the "author" field from package.json, and revert the version bump.请从 package.json 中删除“author”字段，并恢复版本更新。

ok this is my problem, i just modified some file and release my fork version, but i forgot i have pr my branch

**Pull request closed without merging**
